#!/usr/bin/env python3
"""Regenerate brand derivatives from brand/brand.json.

Reads the canonical identity file and writes:

  brand/BRAND.md    human-readable usage (HTML, Slidev, HyperFrames)
  brand/tokens.css  CSS custom properties for standalone HTML and Slidev
  brand/frame.md    HyperFrames camera/frame design spec

Never modifies brand.json or files under brand/assets/. Stdlib only.
Output is deterministic: the same brand.json always yields the same bytes.

Pass --check to validate brand.json and assets, render derivatives in memory,
and exit 0 only when the on-disk files already match. --check never writes.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Mapping

HEX_RE = re.compile(r"^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$")
SEMANTIC_ROLES = ("foreground", "background", "primary", "secondary")
TYPE_ROLES = ("base", "headings", "monospace")
DERIVATIVES = ("BRAND.md", "tokens.css", "frame.md")
GENERATOR = "scripts/brand/generate.py"
SOURCE = "brand/brand.json"

HEADER_MD = (
    "<!-- GENERATED FILE — do not edit.\n"
    f"     Source: {SOURCE}\n"
    f"     Regenerated by: python {GENERATOR}\n"
    "-->\n"
)
HEADER_YAML = (
    "# GENERATED FILE — do not edit.\n"
    f"# Source: {SOURCE}\n"
    f"# Regenerated by: python {GENERATOR}\n"
)
HEADER_CSS = (
    "/* GENERATED FILE — do not edit.\n"
    f" * Source: {SOURCE}\n"
    f" * Regenerated by: python {GENERATOR}\n"
    " */\n"
)


class BrandError(Exception):
    """Invalid or incomplete brand.json."""


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def load_brand(path: Path) -> dict[str, Any]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise BrandError(f"cannot read {path}: {exc}") from exc
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise BrandError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise BrandError("brand.json must be a JSON object")
    return data


def require_mapping(value: Any, path: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise BrandError(f"{path} must be an object")
    return value


def require_str(value: Any, path: str, *, allow_empty: bool = False) -> str:
    if not isinstance(value, str):
        raise BrandError(f"{path} must be a string")
    if not allow_empty and not value.strip():
        raise BrandError(f"{path} must be a non-empty string")
    return value


def require_list(value: Any, path: str) -> list[Any]:
    if not isinstance(value, list) or not value:
        raise BrandError(f"{path} must be a non-empty array")
    return value


def is_hex(value: str) -> bool:
    return bool(HEX_RE.match(value))


def validate(brand: Mapping[str, Any], brand_dir: Path) -> dict[str, Any]:
    meta = require_mapping(brand.get("meta"), "meta")
    name = require_str(meta.get("name"), "meta.name")
    url = require_str(meta.get("url"), "meta.url", allow_empty=True)

    logo = require_mapping(brand.get("logo"), "logo")
    logo_paths: dict[str, str] = {}
    for size in ("small", "medium"):
        size_obj = require_mapping(logo.get(size), f"logo.{size}")
        for variant in ("light", "dark"):
            rel = require_str(size_obj.get(variant), f"logo.{size}.{variant}")
            logo_paths[f"{size}.{variant}"] = rel
            asset = (brand_dir / rel).resolve()
            if not asset.is_file():
                raise BrandError(f"logo.{size}.{variant} file not found: {rel}")
            try:
                asset.relative_to(brand_dir.resolve())
            except ValueError as exc:
                raise BrandError(
                    f"logo.{size}.{variant} must stay under {brand_dir}: {rel}"
                ) from exc

    palette_raw = require_mapping(brand.get("palette"), "palette")
    palette: dict[str, str] = {}
    for key, hex_value in palette_raw.items():
        if not isinstance(key, str) or not key:
            raise BrandError("palette keys must be non-empty strings")
        if not isinstance(hex_value, str) or not is_hex(hex_value):
            raise BrandError(f"palette.{key} must be a #RGB or #RRGGBB hex color")
        palette[key] = hex_value

    color_raw = require_mapping(brand.get("color"), "color")
    color: dict[str, str] = {}
    resolved: dict[str, str] = {}
    for role in SEMANTIC_ROLES:
        token = require_str(color_raw.get(role), f"color.{role}")
        color[role] = token
        resolved[role] = resolve_color(token, palette, f"color.{role}")

    extra_roles = [k for k in color_raw if k not in SEMANTIC_ROLES]
    extra_roles.sort()
    for role in extra_roles:
        token = require_str(color_raw.get(role), f"color.{role}")
        color[role] = token
        resolved[role] = resolve_color(token, palette, f"color.{role}")

    typography = require_mapping(brand.get("typography"), "typography")
    fonts = []
    for index, item in enumerate(require_list(typography.get("fonts"), "typography.fonts")):
        font = require_mapping(item, f"typography.fonts[{index}]")
        family = require_str(font.get("family"), f"typography.fonts[{index}].family")
        source = require_str(font.get("source"), f"typography.fonts[{index}].source")
        weights = require_list(font.get("weight"), f"typography.fonts[{index}].weight")
        for w_i, weight in enumerate(weights):
            if not isinstance(weight, int) or isinstance(weight, bool):
                raise BrandError(
                    f"typography.fonts[{index}].weight[{w_i}] must be an integer"
                )
        styles = font.get("style")
        if styles is None:
            style_list: list[str] = ["normal"]
        else:
            style_list = [
                require_str(s, f"typography.fonts[{index}].style[{i}]")
                for i, s in enumerate(require_list(styles, f"typography.fonts[{index}].style"))
            ]
        fonts.append(
            {
                "family": family,
                "source": source,
                "weight": weights,
                "style": style_list,
            }
        )

    type_roles: dict[str, dict[str, Any]] = {}
    for role in TYPE_ROLES:
        role_obj = require_mapping(typography.get(role), f"typography.{role}")
        family = require_str(role_obj.get("family"), f"typography.{role}.family")
        if not any(f["family"] == family for f in fonts):
            raise BrandError(
                f"typography.{role}.family {family!r} is not listed in typography.fonts"
            )
        entry: dict[str, Any] = {"family": family}
        if "size" in role_obj:
            entry["size"] = require_str(role_obj.get("size"), f"typography.{role}.size")
        if "weight" in role_obj:
            weight = role_obj.get("weight")
            if not isinstance(weight, int) or isinstance(weight, bool):
                raise BrandError(f"typography.{role}.weight must be an integer")
            entry["weight"] = weight
        if "lineHeight" in role_obj:
            line_height = role_obj.get("lineHeight")
            if isinstance(line_height, bool) or not isinstance(line_height, (int, float)):
                raise BrandError(f"typography.{role}.lineHeight must be a number")
            entry["lineHeight"] = line_height
        type_roles[role] = entry

    return {
        "name": name,
        "url": url,
        "logo_paths": logo_paths,
        "palette": palette,
        "color": color,
        "resolved": resolved,
        "fonts": fonts,
        "type_roles": type_roles,
    }


def resolve_color(token: str, palette: Mapping[str, str], path: str) -> str:
    if token in palette:
        return palette[token]
    if is_hex(token):
        return token
    raise BrandError(
        f"{path} value {token!r} is neither a palette name nor a hex color"
    )


def css_ident(name: str) -> str:
    ident = re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-")
    if not ident:
        raise BrandError(f"cannot form a CSS identifier from {name!r}")
    return ident


def font_stack(family: str, kind: str) -> str:
    if kind == "mono":
        fallbacks = "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace"
    else:
        fallbacks = "ui-sans-serif, system-ui, sans-serif"
    return f'"{family}", {fallbacks}'


def google_fonts_url(fonts: list[dict[str, Any]]) -> str | None:
    families: list[str] = []
    for font in fonts:
        if font.get("source") != "google":
            continue
        family = font["family"].replace(" ", "+")
        weights = [str(w) for w in font["weight"]]
        styles = font.get("style") or ["normal"]
        if "italic" in styles:
            pairs = [f"{ital},{w}" for ital in ("0", "1") for w in weights]
            families.append(f"family={family}:ital,wght@{';'.join(pairs)}")
        else:
            families.append(f"family={family}:wght@{';'.join(weights)}")
    if not families:
        return None
    return "https://fonts.googleapis.com/css2?" + "&".join(families) + "&display=swap"


def yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        text = f"{value:.4g}"
        if "." not in text and "e" not in text.lower():
            text = f"{value:.1f}" if value != int(value) else str(int(value))
        return text
    return json.dumps(str(value), ensure_ascii=False)


def yaml_inline_map(mapping: Mapping[str, Any]) -> str:
    parts = [f"{key}: {yaml_scalar(val)}" for key, val in mapping.items()]
    return "{ " + ", ".join(parts) + " }"


def render_tokens_css(model: Mapping[str, Any]) -> str:
    resolved = model["resolved"]
    palette = model["palette"]
    types = model["type_roles"]
    lines = [HEADER_CSS]
    font_url = google_fonts_url(model["fonts"])
    if font_url:
        lines.append(f'@import url("{font_url}");\n')
    lines.append(":root {")
    lines.append("  /* Palette */")
    for name, hex_value in palette.items():
        lines.append(f"  --brand-{css_ident(name)}: {hex_value};")
    lines.append("")
    lines.append("  /* Semantic color */")
    for role in SEMANTIC_ROLES:
        lines.append(f"  --color-{role}: {resolved[role]};")
    extra = [r for r in resolved if r not in SEMANTIC_ROLES]
    extra.sort()
    for role in extra:
        lines.append(f"  --color-{css_ident(role)}: {resolved[role]};")
    if "slate" in palette and "muted" not in resolved:
        lines.append(f"  --color-muted: {palette['slate']};")
    if "lavender" in palette and "accent" not in resolved:
        lines.append(f"  --color-accent-soft: {palette['lavender']};")
    lines.append("")
    lines.append("  /* Typography */")
    lines.append(f"  --font-sans: {font_stack(types['base']['family'], 'sans')};")
    lines.append(
        f"  --font-heading: {font_stack(types['headings']['family'], 'sans')};"
    )
    lines.append(
        f"  --font-mono: {font_stack(types['monospace']['family'], 'mono')};"
    )
    if "size" in types["base"]:
        lines.append(f"  --font-size-base: {types['base']['size']};")
    if "weight" in types["base"]:
        lines.append(f"  --font-weight-base: {types['base']['weight']};")
    if "lineHeight" in types["base"]:
        lines.append(f"  --line-height-base: {types['base']['lineHeight']};")
    if "weight" in types["headings"]:
        lines.append(f"  --font-weight-heading: {types['headings']['weight']};")
    if "lineHeight" in types["headings"]:
        lines.append(f"  --line-height-heading: {types['headings']['lineHeight']};")
    if "size" in types["monospace"]:
        lines.append(f"  --font-size-mono: {types['monospace']['size']};")
    lines.append("")
    lines.append("  /* Slidev aliases */")
    lines.append("  --slidev-theme-primary: var(--color-primary);")
    lines.append("  --slidev-theme-background: var(--color-background);")
    lines.append("  --slidev-font-sans: var(--font-sans);")
    lines.append("  --slidev-font-mono: var(--font-mono);")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def md_table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |"]
    out.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        out.append("| " + " | ".join(row) + " |")
    return "\n".join(out)


def render_brand_md(model: Mapping[str, Any]) -> str:
    name = model["name"]
    url = model["url"]
    resolved = model["resolved"]
    palette = model["palette"]
    types = model["type_roles"]
    logos = model["logo_paths"]
    link_line = url if url else "(none)"
    font_rows = []
    for font in model["fonts"]:
        weights = ", ".join(str(w) for w in font["weight"])
        styles = ", ".join(font["style"])
        font_rows.append([font["family"], font["source"], weights, styles])
    role_rows = []
    for role in TYPE_ROLES:
        entry = types[role]
        bits = [f"family `{entry['family']}`"]
        if "size" in entry:
            bits.append(f"size `{entry['size']}`")
        if "weight" in entry:
            bits.append(f"weight `{entry['weight']}`")
        if "lineHeight" in entry:
            bits.append(f"line-height `{entry['lineHeight']}`")
        role_rows.append([role, ", ".join(bits)])
    color_rows = [
        [role, f"`{model['color'][role]}`", f"`{resolved[role]}`"]
        for role in SEMANTIC_ROLES
    ]
    extra = [r for r in model["color"] if r not in SEMANTIC_ROLES]
    extra.sort()
    for role in extra:
        color_rows.append([role, f"`{model['color'][role]}`", f"`{resolved[role]}`"])
    palette_rows = [[n, f"`{h}`"] for n, h in palette.items()]
    logo_rows = [
        ["small / light backgrounds", f"`brand/{logos['small.light']}`"],
        ["small / dark backgrounds", f"`brand/{logos['small.dark']}`"],
        ["medium / light backgrounds", f"`brand/{logos['medium.light']}`"],
        ["medium / dark backgrounds", f"`brand/{logos['medium.dark']}`"],
    ]
    lines = [
        HEADER_MD,
        f"# {name} brand",
        "",
        "Canonical identity lives in `brand/brand.json`. This file is generated for humans.",
        "Do not hand-edit derivatives; change `brand.json` and re-run the generator.",
        "",
        "## Identity",
        "",
        md_table(["Field", "Value"], [["Name", name], ["URL", link_line]]),
        "",
        "## Logos",
        "",
        "Paths are relative to the workspace root. Use the **light** mark on light grounds",
        "and the **dark** (inverted) mark on dark grounds. Never recolor, stretch, or",
        "outline the SVG.",
        "",
        md_table(["Use", "File"], logo_rows),
        "",
        "## Palette",
        "",
        md_table(["Token", "Hex"], palette_rows),
        "",
        "## Semantic color",
        "",
        md_table(["Role", "Token", "Hex"], color_rows),
        "",
        "## Typography",
        "",
        md_table(["Family", "Source", "Weights", "Styles"], font_rows),
        "",
        md_table(["Role", "Spec"], role_rows),
        "",
        "## Consume in HTML documents",
        "",
        "From a project under `projects/<name>/`, import shared tokens:",
        "",
        "```html",
        '<link rel="stylesheet" href="../../brand/tokens.css">',
        "```",
        "",
        "Use semantic variables (`--color-primary`, `--font-sans`, `--font-heading`)",
        "instead of hardcoded hex or font names. Place `brand/"
        + logos["medium.light"]
        + "` in headers on light pages.",
        "",
        "## Consume in Slidev",
        "",
        "Import the same stylesheet from the deck (for example in `slides.md` or a theme CSS file):",
        "",
        "```css",
        '@import "../../brand/tokens.css";',
        "```",
        "",
        "`tokens.css` aliases `--slidev-theme-primary`, `--slidev-theme-background`,",
        "`--slidev-font-sans`, and `--slidev-font-mono` so Slidev chrome follows the brand.",
        "",
        "## Consume in HyperFrames",
        "",
        "Read `brand/frame.md` first. Frontmatter hex values and font families are normative.",
        "Bind them onto the composition root; do not invent a second accent or substitute fonts.",
        "",
        "## Regenerate",
        "",
        "```bash",
        f"python {GENERATOR}",
        "```",
        "",
        "The generator validates required fields, rewrites only the three derivative files,",
        "and never modifies `brand.json` or `brand/assets/`.",
        "",
    ]
    return "\n".join(lines)


def render_frame_md(model: Mapping[str, Any]) -> str:
    name = model["name"]
    resolved = model["resolved"]
    palette = model["palette"]
    types = model["type_roles"]
    logos = model["logo_paths"]
    muted = palette.get("slate", resolved["foreground"])
    soft = palette.get("lavender", resolved["primary"])
    body = types["base"]
    headings = types["headings"]
    mono = types["monospace"]
    heading_weight = headings.get("weight", 600)
    body_weight = body.get("weight", 400)
    body_lh = body.get("lineHeight", 1.6)
    heading_lh = headings.get("lineHeight", 1.25)
    display = {
        "fontFamily": headings["family"],
        "cqw": 4.2,
        "weight": heading_weight,
        "lineHeight": heading_lh,
        "color": "text",
    }
    title = {
        "fontFamily": headings["family"],
        "cqw": 2.6,
        "weight": heading_weight,
        "lineHeight": heading_lh,
        "color": "text",
    }
    body_type = {
        "fontFamily": body["family"],
        "cqw": 0.85,
        "weight": body_weight,
        "lineHeight": body_lh,
        "color": "text-muted",
    }
    mono_type = {
        "fontFamily": mono["family"],
        "cqw": 0.7,
        "weight": 500,
        "color": "secondary",
    }
    fm = [
        "---",
        HEADER_YAML.rstrip(),
        "version: alpha",
        f"name: {yaml_scalar(name + ' — Frame')}",
        "description: >",
        f"  Video-first companion to the {name} brand. Atoms are the shared palette",
        f"  (primary {resolved['primary']}, secondary {resolved['secondary']},",
        f"  ground {resolved['background']}, ink {resolved['foreground']}) and",
        f"  {headings['family']} + {mono['family']}. Composition is free; numbers",
        "  come from the script.",
        f"unit: {yaml_scalar('the frame — 1920×1080 primary; 9:16 and 1:1 documented')}",
        f"principle: {yaml_scalar('atoms are sacred · composition is free · numbers come from the script')}",
        "",
        "colors:",
        f"  bg: {yaml_scalar(resolved['background'])}",
        f"  primary: {yaml_scalar(resolved['primary'])}",
        f"  secondary: {yaml_scalar(resolved['secondary'])}",
        f"  text: {yaml_scalar(resolved['foreground'])}",
        f"  text-muted: {yaml_scalar(muted)}",
        f"  accent-soft: {yaml_scalar(soft)}",
        f"  logo-light: {yaml_scalar('brand/' + logos['medium.light'])}",
        f"  logo-dark: {yaml_scalar('brand/' + logos['medium.dark'])}",
        "",
        "typography:",
        f"  body: {yaml_inline_map(body_type)}",
        f"  h2: {yaml_inline_map(title)}",
        f"  h1: {yaml_inline_map(display)}",
        f"  mono: {yaml_inline_map(mono_type)}",
        "",
        "spacing:",
        '  pad-x: "5cqw"',
        '  pad-y-top: "5cqw"',
        '  gap: "1.4cqw"',
        "",
        "components:",
        "  cta:",
        f"    backgroundColor: {yaml_scalar(resolved['primary'])}",
        f"    textColor: {yaml_scalar(resolved['background'])}",
        f"    fontFamily: {yaml_scalar(headings['family'])}",
        "    description: Solid primary button. One per closing frame.",
        "  accent-rule:",
        f"    backgroundColor: {yaml_scalar(resolved['primary'])}",
        f"    size: {yaml_scalar('60px × 4px')}",
        "    description: Above cover titles / section separators.",
        "---",
        "",
        f"# {name} — Frame",
        "",
        "## Overview",
        "",
        f"{name} at frame scale is a **light-ground product system** with one violet",
        f"accent (`{resolved['primary']}`) and indigo as the supporting secondary",
        f"(`{resolved['secondary']}`). Ink is `{resolved['foreground']}` on",
        f"`{resolved['background']}`. Type is **{headings['family']}** for display and",
        f"body, **{mono['family']}** for labels, counters, and code.",
        "",
        "Brand atoms are sacred. Layout, density, and motion stay free as long as hex",
        "values and font families match this spec exactly.",
        "",
        "## The Frame",
        "",
        "- **Primary:** 1920×1080 (16:9). Author display sizes in `cqw`.",
        "- **Vertical:** 1080×1920 (9:16). **Square:** 1080×1080 (1:1).",
        "- **Safe area:** `pad-x` / `pad-y-top` 5cqw.",
        "- **Container law:** every frame ground sets `container-type: size`; use `cqw`",
        "  against it, never `vw`.",
        "",
        "## Colors",
        "",
        f"- Ground `{resolved['background']}` (`colors.bg`).",
        f"- Primary accent `{resolved['primary']}` — CTAs, rules, active marks.",
        f"- Secondary `{resolved['secondary']}` — supporting chrome, not a second brand.",
        f"- Text `{resolved['foreground']}`; muted `{muted}` for captions.",
        f"- Soft accent `{soft}` only as a tint, never as fill for body text.",
        f"- Logo: `{logos['medium.light']}` on light grounds; `{logos['medium.dark']}` on dark grounds.",
        "",
        "## Typography",
        "",
        f"- Headings: {headings['family']} weight {heading_weight}, line-height {heading_lh}.",
        f"- Body: {body['family']} weight {body_weight}, line-height {body_lh}.",
        f"- Mono / chrome: {mono['family']}.",
        "- Legibility floor: load-bearing copy ≥ 1.4cqw.",
        "- Do not substitute fonts. Do not italicize headings for emphasis.",
        "",
        "## Composition Rules",
        "",
        "### Do",
        "",
        f"- Start frames on `{resolved['background']}` unless the shot is explicitly dark.",
        f"- Let `{resolved['primary']}` carry the single accent moment per frame.",
        f"- Keep headlines in `{resolved['foreground']}`; reserve primary for marks and CTAs.",
        f"- Pair {headings['family']} display with {mono['family']} metadata.",
        "",
        "### Don't",
        "",
        "- Do not invent hex values or a third accent color.",
        "- Do not recolor, stretch, or outline the logo SVGs.",
        "- Do not use muted slate as a fill for large surfaces.",
        "- Do not fabricate figures; numbers come from the script.",
        "",
        "## Numerals & Claims",
        "",
        "Never invent metrics, dates, or percentages. Render unset values as placeholders",
        "(`— figure —`, `{metric}`) until the script supplies them.",
        "",
        "## Pre-Render Self-Audit",
        "",
        f"- Every hex in the composition appears in this spec (`{resolved['background']}`,",
        f"  `{resolved['foreground']}`, `{resolved['primary']}`, `{resolved['secondary']}`,",
        f"  `{muted}`, `{soft}`).",
        f"- Fonts are exactly {headings['family']} and {mono['family']}.",
        "- One primary accent moment per frame.",
        "- Logo variant matches ground (light vs dark).",
        "",
    ]
    return "\n".join(fm)


def write_text(path: Path, content: str) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(normalize_text(content))


def normalize_text(content: str) -> str:
    if not content.endswith("\n"):
        content += "\n"
    return content


def load_model(brand_dir: Path) -> dict[str, Any]:
    return validate(load_brand(brand_dir / "brand.json"), brand_dir)


def render_all(model: Mapping[str, Any]) -> dict[str, str]:
    writers = {
        "BRAND.md": render_brand_md,
        "tokens.css": render_tokens_css,
        "frame.md": render_frame_md,
    }
    return {name: normalize_text(writers[name](model)) for name in DERIVATIVES}


def generate(brand_dir: Path) -> list[Path]:
    expected = render_all(load_model(brand_dir))
    written: list[Path] = []
    for name in DERIVATIVES:
        path = brand_dir / name
        write_text(path, expected[name])
        written.append(path)
    return written


def check(brand_dir: Path) -> list[tuple[str, Path]]:
    """Compare on-disk derivatives to an in-memory render. Does not write."""
    expected = render_all(load_model(brand_dir))
    problems: list[tuple[str, Path]] = []
    for name in DERIVATIVES:
        path = brand_dir / name
        if not path.is_file():
            problems.append(("missing", path))
            continue
        actual = path.read_bytes()
        if actual != expected[name].encode("utf-8"):
            problems.append(("stale", path))
    return problems


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate brand.json and regenerate BRAND.md, tokens.css, and frame.md."
    )
    parser.add_argument(
        "--brand-dir",
        type=Path,
        default=None,
        help="Brand directory (default: <repo>/brand)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate and compare derivatives in memory; do not write files.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    brand_dir = (args.brand_dir or (repo_root() / "brand")).resolve()
    try:
        if args.check:
            problems = check(brand_dir)
        else:
            written = generate(brand_dir)
    except BrandError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    if args.check:
        if problems:
            print("error: generated files are not current:", file=sys.stderr)
            for status, path in problems:
                print(f"  {status}: {path}", file=sys.stderr)
            return 1
        print("ok")
        return 0
    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
