project:
  type: default
  output-dir: _output
  render:
    - index.qmd

brand: ../../_brand.yml

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    embed-resources: false

  typst:
    toc: true
    number-sections: false
    papersize: a4
    margin:
      x: 2.5cm
      y: 2.5cm

  docx:
    reference-doc: _reference.docx
    toc: true
    number-sections: false
